#version: '3.8'
services:
    http:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: ps10
      environment:
        VIRTUAL_HOST: ps10.in
        VIRTUAL_PORT: 80
        LETSENCRYPT_HOST: ps10.in
        LETSENCRYPT_EMAIL: info@itasca.co.in
      volumes:
        - ps10_volume:/var/www/html/
      networks:
        - external_network_nginx
        - internal_network
      depends_on: filemanager
      expose:
        - 80
    filemanager:
      image: tinyfilemanager/tinyfilemanager
      container_name: filemanager
      volumes:
        - ps10_volume:/var/www/html/data
      expose:
        - 80
      networks:
        - internal_network

volumes:
  ps10_volume:
    driver: local



networks:
  external_network_nginx:
    external: true
  internal_network:
    driver: bridge
