#version: '3.8'
services:
    http:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: cloudywingmedia
      environment:
        VIRTUAL_HOST: cloudywingmedia.com
        VIRTUAL_PORT: 80
        LETSENCRYPT_HOST: cloudywingmedia.com
        LETSENCRYPT_EMAIL: info@cloudywingmedia.com
      volumes:
        -  cloudywingmedia_volume:/var/www/html/
      depends_on:
        - filemanager
      expose:
        - 80
      networks:
        - external_network_nginx
        - internal_network
    filemanager:
      image: filebrowser/filebrowser
      container_name: filemanager
      volumes:
        - ./config.json:/config/filebrowser.json
        - cloudywingmedia_volume:/srv
        - ./filebrowser.db:/database/filebrowser.db
      expose:
        - 80
      environment:
        PUID: $(id -u)
        PGID: $(id -g)
        VIRTUAL_HOST: filemanager.cloudywingmedia.com
        VIRTUAL_PORT: 80
        LETSENCRYPT_HOST: filemanager.cloudywingmedia.com
        LETSENCRYPT_EMAIL: info@cloudywingmedia.com
      networks:
        - external_network_nginx
        - internal_network

volumes:
  cloudywingmedia_volume:
    driver: local
  data_volume:
    driver: local

networks:
  external_network_nginx:
    external: true
  internal_network:
    driver: bridge
