#version: '3.8'
services:
    http:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: ps10
      environment:
        VIRTUAL_HOST: ps10.in
        VIRTUAL_PORT: 80
        LETSENCRYPT_HOST: ps10.in
        LETSENCRYPT_EMAIL: info@itasca.co.in
      volumes:
        - ps10_volume:/var/www/html/
      depends_on:
        - filemanager
      expose:
        - 80
      networks:
        - external_network_nginx
        - internal_network
    filemanager:
      image: filebrowser/filebrowser
      container_name: filemanager
      volumes:
        - ./src/config.json:/config/filebrowser.json
        - ps10_volume:/srv

      expose:
        - 80
      environment:
        VIRTUAL_HOST: filemanager.ps10.in
        VIRTUAL_PORT: 80
        LETSENCRYPT_HOST: filemanager.ps10.in
        LETSENCRYPT_EMAIL: info@yourdomain.com
      networks:
        - external_network_nginx
        - internal_network

volumes:
  ps10_volume:
    driver: local

networks:
  external_network_nginx:
    external: true
  internal_network:
    driver: bridge
